### ISSUE TITLE
Issue with Custom Extension (Possible string formatting issue)

### ISSUE THREAD

**Issue by CommandLineDesign** [chrissimpkins/glue#29]
I'm trying to use Glue to set up some commands to work with the SourceGear Vault source control my company uses. I created a custom extension to attempt to execute some commands and I've hit a road block.

![gitbashresult](https://cloud.githubusercontent.com/assets/6299736/5153099/f211b7aa-71c9-11e4-85be-865ef273ca9c.png)

![glueresult](https://cloud.githubusercontent.com/assets/6299736/5153100/f3bacc22-71c9-11e4-82e3-dc717e72c72a.png)

I've got my extension to the point where the command matches the working GitBash command 100% but my --repository command is still cut off at the empty space.

Edit: Forgot to include the code:

![image](https://cloud.githubusercontent.com/assets/6299736/5153135/11abc036-71cc-11e4-8b25-49fd42809497.png)

**Comment by chrissimpkins** [comment]
collaborative development :) thanks for the comment
