### ISSUE TITLE
Glue doesn't work with subl.exe

### ISSUE THREAD

**Issue by jaichandra** [chrissimpkins/glue#31]
Glue doesn't work when sublime is opened using subl.exe command. None of the Window commands work. But when I open sublime editor using the programs shortcut link, the commands work.

**Comment by chrissimpkins** [comment]
Can you open the Sublime Text console and confirm that it is loading the plug in?   


What version of ST are you using?

**Comment by jaichandra** [comment]
Yes. 'glue path' shows the env variables. but commands like 'dir' or other
console commands doesn't work. Im on windows ST 3 build 3065

**Comment by chrissimpkins** [comment]
I would check to see if you can get some feedback from the Sublime Text forums.  My knowledge about Windows versions of ST is minimal and it sounds as though this is a Sublime Text launch issue on Windows boxes.  Let me know what you learn. -C

**Comment by jaichandra** [comment]
Hey,

I just signed the petition "Ripple Company. : Ripple Company Responsible
for Bitsane Exchange Scam, As they suggested this Exchange." and wanted to
see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/7TSNMnVkcc

Thanks!
Jai

**Comment by jaichandra** [comment]
Hi,

Please ignore the petition email previously sent from my account. That's a
SPAM.
Apologies for the inconvenience.

Thanks
Jai
