### ISSUE TITLE
No such file or directory error when starting node server

### ISSUE THREAD

**Issue by mannyhenri** [chrissimpkins/glue#32]
I right click the directory in sublime, then did LS which as you've seen seem to be in the right directory. 

I can't start the node server by the usual commands for this specific project.And yet it works well in terminal shell. Any ideas? 
![screen shot 2015-02-18 at 10 17 07 am](https://cloud.githubusercontent.com/assets/8015930/6249798/9cb03cc2-b757-11e4-8b98-49b7c4eb7324.png)
![screen shot 2015-02-18 at 10 19 07 am](https://cloud.githubusercontent.com/assets/8015930/6249799/9f00a264-b757-11e4-8ebc-bd51933ca0e8.png)

**Comment by chrissimpkins** [comment]
will you show me the result of these environment variables from inside Glue?

`echo $SHELL`

`echo $PWD`

**Comment by mannyhenri** [comment]
█ [ /Users/manny/Sites/Code Samples/GITHUB/eddy ] pwd
/Users/manny/Sites/Code Samples/GITHUB/eddy

█ [ /Users/manny/Sites/Code Samples/GITHUB/eddy ] echo $SHELL
/bin/bash

█ [ /Users/manny/Sites/Code Samples/GITHUB/eddy ] echo $PWD
/Users/manny/Sites/Code Samples/GITHUB/eddy

 


From:  Chris Simpkins
Reply-To:  chrissimpkins/glue
Date:  Thursday, February 19, 2015 at 12:49 PM
To:  chrissimpkins/glue
Cc:  Manny Henri
Subject:  Re: [glue] No such file or directory error when starting node 
server (#32)


will you show me the result of these environment variables from inside 
Glue?

echo $SHELL

echo $PWD

**Comment by chrissimpkins** [comment]
The glue command pwd matches the actual present working directory in the shell that is spawned to run the command.  Your node.js based apps should have access to any of the files in the working directory.  

That looks like an exception from your shell environment.  It looks like node is not on the system PATH available to the shell spawned by Glue.  Glue attempts to read your PATH settings but in some circumstances they aren't correct.  Can you confirm whether this is the case?  ([Link to docs info on Glue paths](http://gluedocs.readthedocs.org/en/latest/install.html#confirm-your-path)).

Here is [how you modify the Glue PATH](http://gluedocs.readthedocs.org/en/latest/install.html#change-your-path-settings) if that seems to be the problem.

Let me know if that helps. -C

**Comment by chrissimpkins** [comment]
any luck with this?

**Comment by mannyhenri** [comment]
Not yet 

Thanks
Manny




On Sat, Feb 21, 2015 at 2:09 PM -0800, "Chris Simpkins" <notifications@github.com> wrote:












any luck with this?

**Comment by chrissimpkins** [comment]
thanks Manny.  Let me know when you have the chance to try it. -C

**Comment by mannyhenri** [comment]
@chrissimpkins I haven't been able to answer since I've moved to using Webstorm now. Last I checked the issue was resolved (before the switch).

**Comment by chrissimpkins** [comment]
OK thanks!
