### ISSUE TITLE
Package manager can't find Glue plugin

### ISSUE THREAD

**Issue by theasder** [chrissimpkins/glue#33]
I am using ST 3 under OS X 10.10.

**Comment by chrissimpkins** [comment]
It is showing up for me on OSX in ST3.  If you already have it installed, it will not show up when you try `Package Control - Install Package`.  It's under `Package Control - Upgrade Package`.

Let me know if that helps.

**Comment by theasder** [comment]
All right, I just haven't noticed, it was installed, sorry :)

**Comment by chrissimpkins** [comment]
no worries at all! let me know if you have any questions.
