### ISSUE TITLE
Glue terminal not being displayed with Material Theme applied

### ISSUE THREAD

**Issue by TJohnson93** [chrissimpkins/glue#38]
Hi, When a theme is applied (I tried Material Theme) the Glue terminal is not displayed.

**Comment by chrissimpkins** [comment]
did you intend to close this issue?

**Comment by TJohnson93** [comment]
Yes it turns out it was a Theme issue... Sorry for any inconvenience.

**Comment by chrissimpkins** [comment]
no worries!
