### ISSUE TITLE
output not printing

### ISSUE THREAD

**Issue by lukecfairchild** [chrissimpkins/glue#41]
So I just installed glue.
I am using the following:
mac osx10.10.5
Sublime Text, Build 3083

Install steps done:
Installed using Package control by adding this git repo
set Glue.sublime-settings to:
{
	"glue_userpath" : "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
}
the path was gotten from cmdline using the command echo $PATH

After all that I would open up glues terminal thing from both command palette and from right clicking on a project.
When i enter any command it shows no output. Commands that I tried:
ls
cd ../
glue help
glue path
glue clear

All that is shown is the terminal.glue file with the original help stuff.

When I do glue new it opens a new blank untitled tab with nothing in it. When I do any commands it remains blank, though the command bar thing does flicker.

In addition from command palette if i try to run glue path, it does nothing.
Hope this is enough detail.

**Comment by lukecfairchild** [comment]
Ok so weird thing just happened. I closed the original terminal.glue file and then did exit on another terminal and it started printing.. So it may of fixed itself not sure why but i would still say this can be a issue possibly. Do what you like with this. Awesome stuff though.

**Comment by chrissimpkins** [comment]
Thanks Luke.  This isn't under active development but happy to try to help address any issues that come up.  Please let me know if you continue to experience problems.

**Comment by lukecfairchild** [comment]
O thats sad to hear, but thanks for the offer.

**Comment by chrissimpkins** [comment]
May take this up again.  testing within the embedded Python in the editors has been tough and tedious.  Always accepting pull requests though!

**Comment by lukecfairchild** [comment]
I've never coded in python before but i may look into the highlighting feature. About that when you execute a command do you get the color codes back and strip them? Or does it never give you them?

**Comment by chrissimpkins** [comment]
The ANSI codes do not get interpreted.  There is not currently colored output support.  This would have to be done through some form of syntax highlighter.  I would need to look back to see but I think I stripped the codes out so that the text displays properly

**Comment by lukecfairchild** [comment]
Yeah I know its currently not supported. I was looking at the feature request earlier for it.

**Comment by destroy-everything** [comment]
same problem never got it solved...

**Comment by samIntegrateur** [comment]
I have the same issue, but I'm on Windows 10 and nothing happens even when closing all windows
